# question_data = [
# {"text": "A slug's blood is green.", "answer": "True"},
# {"text": "The loudest animal is the African Elephant.", "answer": "False"},
# {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
# {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
# {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
# {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
# {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
# {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
# {"text": "Google was originally called 'Backrub'.", "answer": "True"},
# {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
# {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
# {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = {"response_code": 0,
                 "results": [
                     {"category": "Entertainment: Music",
                      "type": "boolean",
                      "difficulty": "easy",
                      "question": "The music group Daft Punk got their name from a negative review they recieved.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Animals", "type": "boolean", "difficulty": "easy",
                      "question": "A bear does NOT defecate during hibernation. ", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "History", "type": "boolean", "difficulty": "medium",
                      "question": "Theodore Roosevelt Jr. was the only General involved in the initial assault on D-Day.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "Toronto is the capital city of the North American country of Canada.",
                      "correct_answer": "False",
                      "incorrect_answers": ["True"]},
                     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
                      "question": "Arriva is owned by the Deutsche Bahn.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                      "question": "In &quot;Star Trek&quot;, Klingons respect William Shakespeare, they even suspect him having a Klingon lineage.",
                      "correct_answer": "True", "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
                      "question": "In Portal, the Companion Cube&#039;s ARE sentient.", "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
                      "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
                      "correct_answer": "True",
                      "incorrect_answers": ["False"]},
                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                      "question": "New Haven is the capital city of the state of Connecticut in the United States.",
                      "correct_answer": "False", "incorrect_answers": ["True"]},
                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                      "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
                      "correct_answer": "True", "incorrect_answers": ["False"]}]}
